"""Shared helpers for ingest routers (local and online)."""

from app.models.common import ErrorCode

INGEST_ERROR_CODE_MAP = {
    "VALIDATION_EMPTY_CONTENT": ErrorCode.VALIDATION_EMPTY_CONTENT,
    "VALIDATION_ACL_REQUIRED": ErrorCode.VALIDATION_ACL_REQUIRED,
    "EMBEDDING_MODEL_NOT_LOADED": ErrorCode.EMBEDDING_MODEL_NOT_LOADED,
    "EMBEDDING_FAILED": ErrorCode.EMBEDDING_FAILED,
    "EMBEDDING_OOM": ErrorCode.EMBEDDING_OOM,
    "QDRANT_CONNECTION_FAILED": ErrorCode.QDRANT_CONNECTION_FAILED,
    "QDRANT_COLLECTION_NOT_FOUND": ErrorCode.QDRANT_COLLECTION_NOT_FOUND,
    "QDRANT_UPSERT_FAILED": ErrorCode.QDRANT_UPSERT_FAILED,
    "QDRANT_DISK_FULL": ErrorCode.QDRANT_DISK_FULL,
    "CLASSIFY_FAILED": ErrorCode.CLASSIFY_FAILED,
}
